name: uq_summer_school2024
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.23.0
  - matplotlib=3.8.4
  - netcdf4=1.6.5
  - numpy=1.26.4
  - python=3.9.19
  - xarray=2024.5.0
  - pip
  - pip:
      - gsw==3.6.18
      - gsw-xarray==0.4.0
      - h5netcdf==1.3.0
      - scipy==1.13.1
